In [1]:
import numpy as np

In [6]:
#1
a = np.array([[1, 6], 
              [2, 8], 
              [3, 11], 
              [3, 10], 
              [1, 7]])
mean_a = a.mean(axis = 0)
mean_a

array([2. , 8.4])

In [7]:
#2
a_centered = np.subtract(a, mean_a)
a_centered

array([[-1. , -2.4],
       [ 0. , -0.4],
       [ 1. ,  2.6],
       [ 1. ,  1.6],
       [-1. , -1.4]])

In [16]:
#3
a1 = a_centered[:,0]
a2 = a_centered[:,1]
a_centered_sp = np.dot(a1,a2)
a_centered_sp

8.0

In [19]:
N = a.shape[0]
cov_1 = a_centered_sp/(N-1)
cov_1

2.0

In [20]:
#4
cov_2 = np.cov(a.transpose())
cov_2

array([[1. , 2. ],
       [2. , 4.3]])